config/routes.rb
Rails.application.routes.draw do
  get 'map/index'

  resources :mapusers
  devise_for :users
  root 'posts#index'
  resources :posts do
    resources :comments, only: [:create]
  end
  resources :users, only: [:show]
  resources :instagrams
  get 'donations' => 'donations#index'
  get 'donations/interest' => 'donations#interest'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post               #postsテーブルとのアソシエーション
  belongs_to :user                #usersテーブルとのアソシエーション
end

app/models/google_search_api.rb
class GoogleSearchApi 
  require 'cgi'
  def self.search(search_word_org, limit)                                                                                                                                                                   
    search_word = CGI.escape(search_word_org)
    url = URI("http://ajax.googleapis.com/ajax/services/search/images?v=1.0&key=AIzaSyCYco6F1UzYt0crJ92KRe_B1aSpy3s4nwQ&q=#{search_word}&rsz=#{limit}")                                                                                      
    http = Net::HTTP.new(url.host)                                                                                                                                                                       
    response = http.get(url.request_uri)
    response_data = JSON.parse(response.body)
    if response_data['responseStatus'] == 403                                                                                                                                                            
      return image_list = nil
    end
    response_data
    # image_list = response_data['responseData']['results']
  end 
end 

app/models/mapuser.rb
class Mapuser < ActiveRecord::Base
  geocoded_by :address
  after_validation :geocode
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments               #commentsテーブルとのアソシエーション
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :nickname
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(text: comment_params[:text], post_id: comment_params[:post_id], user_id: current_user.id)
    redirect_to "/posts/#{@comment.post.id}"   #ポストと結びつくツイートの詳細画面に遷移する
  end

  private
  def comment_params
    params.permit(:text, :post_id)
  end
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  def index
  end
end

app/controllers/instagrams_controller.rb
class InstagramsController < ApplicationController

    def index
        @medias = Instagram.tag_recent_media("スニーカー")
    end
end

app/controllers/mapusers_controller.rb
class MapusersController < ApplicationController
  before_action :set_mapuser, only: [:show, :edit, :update, :destroy]

  # GET /mapusers
  # GET /mapusers.json
  def index
    @mapusers = Mapuser.all
  end

  # GET /mapusers/1
  # GET /mapusers/1.json
  def show
  end

  # GET /mapusers/new
  def new
    @mapuser = Mapuser.new
  end

  # GET /mapusers/1/edit
  def edit
  end

  # POST /mapusers
  # POST /mapusers.json
  def create
    @mapuser = Mapuser.new(mapuser_params)

    respond_to do |format|
      if @mapuser.save
        format.html { redirect_to @mapuser, notice: 'Mapuser was successfully created.' }
        format.json { render :show, status: :created, location: @mapuser }
      else
        format.html { render :new }
        format.json { render json: @mapuser.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mapusers/1
  # PATCH/PUT /mapusers/1.json
  def update
    respond_to do |format|
      if @mapuser.update(mapuser_params)
        format.html { redirect_to @mapuser, notice: 'Mapuser was successfully updated.' }
        format.json { render :show, status: :ok, location: @mapuser }
      else
        format.html { render :edit }
        format.json { render json: @mapuser.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mapusers/1
  # DELETE /mapusers/1.json
  def destroy
    @mapuser.destroy
    respond_to do |format|
      format.html { redirect_to mapusers_url, notice: 'Mapuser was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mapuser
      @mapuser = Mapuser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mapuser_params
      params.require(:mapuser).permit(:title, :description, :address, :latitude, :longitude)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :move_to_index, except: :index

  def index
    @posts = Post.includes(:user).order("id DESC")
  end

  def new
  end

  def create
    Post.create(image: post_params[:image], text: post_params[:text], user_id: current_user.id)
  end

  def destroy
    post = Post.find(params[:id])
    if post.user_id == current_user.id
      post.destroy
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    if post.user_id == current_user.id
      post.update(post_params)
    end
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.includes(:user)
  end

  private
  def post_params
    params.permit(:image, :text)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @posts = user.posts.order("created_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/helpers/instagram_helper.rb
module InstagramHelper
end

app/helpers/instagrams_helper.rb
module InstagramsHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/helpers/mapusers_helper.rb
module MapusersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/donations/index.html.erb
<div class="donations_title">
  <p>footpostへの寄付をお願いいたします</p>
</div>


<div class="donations_contents">
  <p>今週は皆様にお知らせがあります。footpostへの援助をお願いいたします。 私たちは独立性を守るため、一切の広告を掲載致しません。 平均約¥1,500の寄付で運営しております。 援助をして下さる読者はほんの少数です。 お願い致します。 今日、読者の皆様が¥700ご援助下されば、寄付の募集は一時間で終了です。 footpostを活用しておられるのでしたら、広告掲載せずにさらに1年活動できるよう、どうか1分の時間をお取り下さい。 私たちは小さな非営利組織ですが、サーバー、プログラム、人件費など、世界でトップクラスのウェブサイト同様のコストがかかります。 利用者は何百万人もいますが、他の大きなサイトに比べほんの少額の費用で運営しているのです。 ウィキペディアは特別です。誰でも活用できる図書館や公園のようです。 footpostは、世界中の知識の相互活用に情熱を抱くボランティア達によって書かれています。 募金活動を終了し、footpost改善の活動に戻れるようご援助ください。 宜しくお願い致します。</p>
</div>


<div class="donations_btn">
  <script src="https://checkout.webpay.jp/v1/" class="webpay-button" data-key="<%= WEBPAY_PUBLIC_KEY %>"></script>
</div>

app/views/donations/interest.html.erb
<div id="form">
    <p class="form-title">足もとの好みを登録</p>
    <form action="post">
        <p>好きな靴のブランド</p>
        <p class="field"><input type="email" name="mail" /></p>
        <p>好きな靴のタイプ</p>
        <p class="field"><input type="password" name="pass" /></p>
        <p>今欲しい靴の型番</p>
        <p class="field"><input type="email" name="mail" /></p>
        <p>好きな色</p>
        <p class="field"><input type="password" name="pass" /></p>
        <p class="field"><input type="submit" value="好みを登録" /></p>
    </form>
</div>

app/views/instagrams/index.html.erb
<% @medias.each do |media| %>
  <%= link_to media.link, target: "_blank" do %>
    <%= image_tag(media.images.low_resolution.url) %>
  <% end %>
<% end %>

app/views/mapusers/_form.html.erb
<%= form_for(@mapuser) do |f| %>
  <% if @mapuser.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mapuser.errors.count, "error") %> prohibited this mapuser from being saved:</h2>

      <ul>
      <% @mapuser.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mapusers/edit.html.erb
<h1>Editing Mapuser</h1>

<%= render 'form' %>

<%= link_to 'Show', @mapuser %> |
<%= link_to 'Back', mapusers_path %>

app/views/mapusers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Mapusers</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mapusers.each do |mapuser| %>
      <tr>
        <td><%= mapuser.title %></td>
        <td><%= mapuser.description %></td>
        <td><%= mapuser.address %></td>
        <td><%= mapuser.latitude %></td>
        <td><%= mapuser.longitude %></td>
        <td><%= link_to 'Show', mapuser %></td>
        <td><%= link_to 'Edit', edit_mapuser_path(mapuser) %></td>
        <td><%= link_to 'Destroy', mapuser, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mapuser', new_mapuser_path %>

app/views/mapusers/new.html.erb
<h1>New Mapuser</h1>

<%= render 'form' %>

<%= link_to 'Back', mapusers_path %>

app/views/mapusers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @mapuser.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @mapuser.description %>
</p>

<p>
  <strong>Address:</strong>
  <%= @mapuser.address %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @mapuser.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @mapuser.longitude %>
</p>

<%= link_to 'Edit', edit_mapuser_path(@mapuser) %> |
<%= link_to 'Back', mapusers_path %>

app/views/posts/create.html.erb
<div class="contents row">
  <div class="content_post_solo">
    <div class="k_comments">
      <div class="success">
        <h3>
          足元の投稿が完了しました。
        </h3>
        <a class="btn" href="/">投稿一覧へ戻る</a>
      </div>
    </div>
  </div>
</div>

app/views/posts/destroy.html.erb
<div class="contents row">
  <div class="content_post_solo">
    <div class="k_comments">
      <div class="success">
        <h3>
          削除が完了しました。
        </h3>
        <a class="btn" href="/">投稿一覧へ戻る</a>
      </div>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<div class ="contents row">
  <div class="content_post_solo">
    <div class="k_comments">
    <%= form_tag("/posts/#{@post.id}", method: :patch ) do %>
      <h3>
        編集する
      </h3>
      <input placeholder="Image Url" type="text" name="image" value="<%= @post.image %>" autofocus="true">
      <textarea cols="30" name="text" placeholder="text" rows="10"><%= @post.text %></textarea>
      <input type="submit" value="SENT">
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
  <% @posts.each do |post| %>
    <div class="content_post" >
      <div class="content_image" style="background-image: url(<%= post.image %>);">
      </div>

      <div class="k_content_content">


            <ul class="more_list">
              <ul>
                <%= link_to '詳細', "/posts/#{post.id}", method: :get %>
              </ul>
              <ul>
                <%= link_to 'フォロー'%>
              </ul>
              <ul>
                <%= link_to 'どうも！'%>
              </ul>
                <% if user_signed_in? && current_user.id == post.user_id %>
                  <ul>
                    <%= link_to '編集', "/posts/#{post.id}/edit", method: :get %>
                  </ul>
                  <ul>
                    <%= link_to '削除', "/posts/#{post.id}", method: :delete %>
                  </ul>
                <% end %>
            </ul>


        <span class="name">
          <a href="/users/<%= post.user_id %>">
            <span>name: </span><%= post.user.nickname %>
          </a>
        </span>

        <p>
          <%= simple_format(post.text) %>
        </p>

      </div>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="contents row">

    <div class="content_post_solo">
      <div class="k_comments">
        <%= form_tag('/posts', method: :post) do %>
          <h3>
            足元を投稿する
          </h3>
          <input placeholder="Image Url" type="text" name="image">
          <textarea cols="30" name="text" placeholder="text" rows="10"></textarea>
          <input type="submit" value="SENT">
        <% end %>
      </div>
    </div>

</div>

app/views/posts/show.html.erb
<div class ="contents row">
  <div class="content_post_solo">
    <div class="content_image_solo" style="background-image: url(<%= @post.image %>);">
    </div>

      <div class="k_content_content">
        <% if user_signed_in? && current_user.id == @post.user_id %>
            <ul class="more_list">
              <!--<ul>
                <%= link_to '詳細', "/posts/#{@post.id}", method: :get %>
              </ul><-->
              <ul>
                <%= link_to '編集', "/posts/#{@post.id}/edit", method: :get %>
              </ul>
              <ul>
                <%= link_to '削除', "/posts/#{@post.id}", method: :delete %>
              </ul>
            </ul>
        <% end %>
        <span class="name">
          <a href="/users/<%= @post.user_id %>">
            <span>name: </span><%= @post.user.nickname %>
          </a>
          <p>
            <%= simple_format(@post.text) %>
          </p>
        </span>
      </div>

    <!-- ここからフォーム -->
    <div class="k_comments">
      <% if current_user %>
        <%= form_tag("/posts/#{@post.id}/comments", method: :post) do %>
          <textarea cols="30" name="text" placeholder="コメントする" rows="2"></textarea>
          <input type="submit" value="SENT">
        <% end %>
      <% end %>

      <div class="comments">
        <h4>コメント一覧</h4>
        <% if @comments %>
          <% @comments.each do |comment| %>
            <p>
              <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
              <%= comment.text %>
            </p>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/update.html.erb
  <div class="content_post_solo">
    <div class="k_comments">
      <div class="success">
        <h3>
          更新が完了しました。
        </h3>
        <a class="btn" href="/">投稿一覧へ戻る</a>
      </div>
    </div>
  </div>

app/views/users/show.html.erb
<div class="profile_image">
  <%= image_tag 'prfile2.png' %>
</div>

<a href="/donations/interest">足もとの好みの編集</a>

<div class="mypage_title">
  <p><%= @nickname %>さんの投稿一覧</p>
</div>


<% @posts.each do |post| %>
  <div class="content_post" >
  <div class="content_image" style="background-image: url(<%= post.image %>);">

  </div>

  <div class="k_content_content">
  <p>
    <%= simple_format(post.text) %>
  </p>
  <% if user_signed_in? && current_user.id == post.user_id %>
  <ul class="more_list">
        <ul>
          <%= link_to '詳細', "/posts/#{post.id}", method: :get %>
        </ul>
        <% if user_signed_in? && current_user.id == post.user_id %>
          <ul>
            <%= link_to '編集', "/posts/#{post.id}/edit", method: :get %>
          </ul>
          <ul>
            <%= link_to '削除', "/posts/#{post.id}", method: :delete %>
          </ul>
        <% end %>
      </ul>
  <% end %>
  <span class="name">
    <a href="/users/<%= post.user_id %>">
      <span>足元の投稿者</span><%= post.user.nickname %>
    </a>
  </span>
  </div>
</div>
<% end %>